on: Publish Release

on:
  workflow_dispatch:

jobs:
  tag-and-release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Install uv
        uses: astral-sh/setup-uv@5a7eac68fb9809dea845d802897dc5c723910fa3 # v7.1.3
        with:
          version: "0.9.10"

      - name: Config git user
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Create and push tag
        run: |
          TAG=v$(uv version --short)
          git tag $TAG
          git push origin $TAG
